name: Node.js CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The website is deployed on an ubuntu droplet via Digital Ocean at the moment
    runs-on: ubuntu-latest

    # Test on multiple Node.js versions
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # 1. Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the specified version of Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Installs dependencies using npm ci for a clean, deterministic install
      - name: Install dependencies
        run: npm ci

      # 4. Builds the production version of the app
      - name: Build project
        run: npm run build --if-present

      # 5. Runs your tests
      - name: Run tests
        run: npm test
